-- Extended subjects: B.Tech IT/DS/EE/ENC, B.Sc, BCA, MCA, M.Sc, MBA
-- Run in Supabase SQL Editor after attendance_schema.sql

INSERT INTO public.subjects (id, name, code, course, branch, semester, section) VALUES

-- B.Tech IT (8 semesters)
('btech-it-sem1-math','Engineering Mathematics I','MA101','B.Tech','IT',1,'A'),
('btech-it-sem1-prog','Programming Fundamentals','IT101','B.Tech','IT',1,'A'),
('btech-it-sem1-physics','Engineering Physics','PH101','B.Tech','IT',1,'A'),
('btech-it-sem1-comm','Communication Skills','HU101','B.Tech','IT',1,'A'),
('btech-it-sem2-math2','Engineering Mathematics II','MA102','B.Tech','IT',2,'A'),
('btech-it-sem2-ds','Data Structures','IT102','B.Tech','IT',2,'A'),
('btech-it-sem2-chem','Engineering Chemistry','CY102','B.Tech','IT',2,'A'),
('btech-it-sem2-digital','Digital Logic','IT103','B.Tech','IT',2,'A'),
('btech-it-sem3-algo','Algorithms','IT201','B.Tech','IT',3,'A'),
('btech-it-sem3-oop','Object Oriented Programming','IT202','B.Tech','IT',3,'A'),
('btech-it-sem3-dbms','Database Management','IT203','B.Tech','IT',3,'A'),
('btech-it-sem3-math3','Discrete Mathematics','MA201','B.Tech','IT',3,'A'),
('btech-it-sem4-os','Operating Systems','IT204','B.Tech','IT',4,'A'),
('btech-it-sem4-cn','Computer Networks','IT205','B.Tech','IT',4,'A'),
('btech-it-sem4-web','Web Technologies','IT206','B.Tech','IT',4,'A'),
('btech-it-sem4-java','Java Programming','IT207','B.Tech','IT',4,'A'),
('btech-it-sem5-se','Software Engineering','IT301','B.Tech','IT',5,'A'),
('btech-it-sem5-ai','Artificial Intelligence','IT302','B.Tech','IT',5,'A'),
('btech-it-sem5-cloud','Cloud Computing','IT303','B.Tech','IT',5,'A'),
('btech-it-sem5-mobile','Mobile Development','IT304','B.Tech','IT',5,'A'),
('btech-it-sem6-ml','Machine Learning','IT305','B.Tech','IT',6,'A'),
('btech-it-sem6-cyber','Cyber Security','IT306','B.Tech','IT',6,'A'),
('btech-it-sem6-iot','Internet of Things','IT307','B.Tech','IT',6,'A'),
('btech-it-sem6-devops','DevOps Practices','IT308','B.Tech','IT',6,'A'),
('btech-it-sem7-bigdata','Big Data Analytics','IT401','B.Tech','IT',7,'A'),
('btech-it-sem7-blockchain','Blockchain Technology','IT402','B.Tech','IT',7,'A'),
('btech-it-sem7-ar','AR/VR Development','IT403','B.Tech','IT',7,'A'),
('btech-it-sem7-nlp','Natural Language Processing','IT404','B.Tech','IT',7,'A'),
('btech-it-sem8-project','Major Project','IT498','B.Tech','IT',8,'A'),
('btech-it-sem8-ethics','Professional Ethics','HU401','B.Tech','IT',8,'A'),
('btech-it-sem8-startup','Entrepreneurship','MG401','B.Tech','IT',8,'A'),
('btech-it-sem8-audit','IT Audit & Governance','IT405','B.Tech','IT',8,'A'),

-- B.Tech DS (Data Science, 8 semesters)
('btech-ds-sem1-math','Calculus & Linear Algebra','MA101','B.Tech','DS',1,'A'),
('btech-ds-sem1-prog','Python Programming','DS101','B.Tech','DS',1,'A'),
('btech-ds-sem1-stats','Statistics Fundamentals','DS102','B.Tech','DS',1,'A'),
('btech-ds-sem1-comm','Communication Skills','HU101','B.Tech','DS',1,'A'),
('btech-ds-sem2-prob','Probability Theory','MA102','B.Tech','DS',2,'A'),
('btech-ds-sem2-db','Database Systems','DS103','B.Tech','DS',2,'A'),
('btech-ds-sem2-algo','Data Structures & Algorithms','DS104','B.Tech','DS',2,'A'),
('btech-ds-sem2-viz','Data Visualization','DS105','B.Tech','DS',2,'A'),
('btech-ds-sem3-ml1','Machine Learning I','DS201','B.Tech','DS',3,'A'),
('btech-ds-sem3-bigdata','Big Data Technologies','DS202','B.Tech','DS',3,'A'),
('btech-ds-sem3-sql','Advanced SQL','DS203','B.Tech','DS',3,'A'),
('btech-ds-sem3-math3','Multivariate Calculus','MA201','B.Tech','DS',3,'A'),
('btech-ds-sem4-ml2','Machine Learning II','DS204','B.Tech','DS',4,'A'),
('btech-ds-sem4-dl','Deep Learning','DS205','B.Tech','DS',4,'A'),
('btech-ds-sem4-nlp','Natural Language Processing','DS206','B.Tech','DS',4,'A'),
('btech-ds-sem4-cv','Computer Vision','DS207','B.Tech','DS',4,'A'),
('btech-ds-sem5-cloud','Cloud Data Platforms','DS301','B.Tech','DS',5,'A'),
('btech-ds-sem5-mlops','MLOps & Deployment','DS302','B.Tech','DS',5,'A'),
('btech-ds-sem5-rein','Reinforcement Learning','DS303','B.Tech','DS',5,'A'),
('btech-ds-sem5-time','Time Series Analysis','DS304','B.Tech','DS',5,'A'),
('btech-ds-sem6-bi','Business Intelligence','DS305','B.Tech','DS',6,'A'),
('btech-ds-sem6-ethics','Data Ethics & Privacy','DS306','B.Tech','DS',6,'A'),
('btech-ds-sem6-graph','Graph Analytics','DS307','B.Tech','DS',6,'A'),
('btech-ds-sem6-research','Research Methodology','DS308','B.Tech','DS',6,'A'),
('btech-ds-sem7-capstone','Capstone Project I','DS401','B.Tech','DS',7,'A'),
('btech-ds-sem7-fintech','Data Science in Finance','DS402','B.Tech','DS',7,'A'),
('btech-ds-sem7-health','Healthcare Analytics','DS403','B.Tech','DS',7,'A'),
('btech-ds-sem7-elect','Elective','DS404','B.Tech','DS',7,'A'),
('btech-ds-sem8-project','Major Project','DS498','B.Tech','DS',8,'A'),
('btech-ds-sem8-product','Product Analytics','DS405','B.Tech','DS',8,'A'),
('btech-ds-sem8-audit','Data Governance','DS406','B.Tech','DS',8,'A'),
('btech-ds-sem8-ethics2','Professional Ethics','HU401','B.Tech','DS',8,'A'),

-- B.Tech EE (Electrical Engineering, 8 semesters)
('btech-ee-sem1-math','Engineering Mathematics I','MA101','B.Tech','EE',1,'A'),
('btech-ee-sem1-basic','Basic Electrical Engineering','EE101','B.Tech','EE',1,'A'),
('btech-ee-sem1-physics','Engineering Physics','PH101','B.Tech','EE',1,'A'),
('btech-ee-sem1-workshop','Workshop Practice','EE102','B.Tech','EE',1,'A'),
('btech-ee-sem2-math2','Engineering Mathematics II','MA102','B.Tech','EE',2,'A'),
('btech-ee-sem2-circuits','Circuit Theory','EE103','B.Tech','EE',2,'A'),
('btech-ee-sem2-chem','Engineering Chemistry','CY102','B.Tech','EE',2,'A'),
('btech-ee-sem2-digital','Digital Electronics','EE104','B.Tech','EE',2,'A'),
('btech-ee-sem3-machines','Electrical Machines I','EE201','B.Tech','EE',3,'A'),
('btech-ee-sem3-signals','Signals & Systems','EE202','B.Tech','EE',3,'A'),
('btech-ee-sem3-emft','Electromagnetic Theory','EE203','B.Tech','EE',3,'A'),
('btech-ee-sem3-control','Control Systems','EE204','B.Tech','EE',3,'A'),
('btech-ee-sem4-machines2','Electrical Machines II','EE205','B.Tech','EE',4,'A'),
('btech-ee-sem4-power','Power Systems I','EE206','B.Tech','EE',4,'A'),
('btech-ee-sem4-micro','Microprocessors','EE207','B.Tech','EE',4,'A'),
('btech-ee-sem4-measure','Electrical Measurements','EE208','B.Tech','EE',4,'A'),
('btech-ee-sem5-power2','Power Systems II','EE301','B.Tech','EE',5,'A'),
('btech-ee-sem5-drives','Electrical Drives','EE302','B.Tech','EE',5,'A'),
('btech-ee-sem5-pe','Power Electronics','EE303','B.Tech','EE',5,'A'),
('btech-ee-sem5-plc','PLC & Automation','EE304','B.Tech','EE',5,'A'),
('btech-ee-sem6-switchgear','Switchgear & Protection','EE305','B.Tech','EE',6,'A'),
('btech-ee-sem6-hv','High Voltage Engineering','EE306','B.Tech','EE',6,'A'),
('btech-ee-sem6-renewable','Renewable Energy Systems','EE307','B.Tech','EE',6,'A'),
('btech-ee-sem6-dsp','Digital Signal Processing','EE308','B.Tech','EE',6,'A'),
('btech-ee-sem7-smart','Smart Grid Technology','EE401','B.Tech','EE',7,'A'),
('btech-ee-sem7-ev','Electric Vehicles','EE402','B.Tech','EE',7,'A'),
('btech-ee-sem7-scada','SCADA Systems','EE403','B.Tech','EE',7,'A'),
('btech-ee-sem7-elect','Elective','EE404','B.Tech','EE',7,'A'),
('btech-ee-sem8-project','Major Project','EE498','B.Tech','EE',8,'A'),
('btech-ee-sem8-aipower','AI in Power Systems','EE405','B.Tech','EE',8,'A'),
('btech-ee-sem8-energy','Energy Management','EE406','B.Tech','EE',8,'A'),
('btech-ee-sem8-ethics','Professional Ethics','HU401','B.Tech','EE',8,'A'),

-- B.Tech ENC (Electronics & Communication, 8 semesters)
('btech-enc-sem1-math','Engineering Mathematics I','MA101','B.Tech','ENC',1,'A'),
('btech-enc-sem1-basic','Basic Electronics','EC101','B.Tech','ENC',1,'A'),
('btech-enc-sem1-physics','Engineering Physics','PH101','B.Tech','ENC',1,'A'),
('btech-enc-sem1-prog','C Programming','CS101','B.Tech','ENC',1,'A'),
('btech-enc-sem2-math2','Engineering Mathematics II','MA102','B.Tech','ENC',2,'A'),
('btech-enc-sem2-circuits','Network Theory','EC102','B.Tech','ENC',2,'A'),
('btech-enc-sem2-signals','Signals & Systems','EC103','B.Tech','ENC',2,'A'),
('btech-enc-sem2-digital','Digital Electronics','EC104','B.Tech','ENC',2,'A'),
('btech-enc-sem3-analog','Analog Circuits','EC201','B.Tech','ENC',3,'A'),
('btech-enc-sem3-emft','Electromagnetic Fields','EC202','B.Tech','ENC',3,'A'),
('btech-enc-sem3-control','Control Engineering','EC203','B.Tech','ENC',3,'A'),
('btech-enc-sem3-micro','Microcontrollers','EC204','B.Tech','ENC',3,'A'),
('btech-enc-sem4-comm','Analog Communication','EC205','B.Tech','ENC',4,'A'),
('btech-enc-sem4-dcomm','Digital Communication','EC206','B.Tech','ENC',4,'A'),
('btech-enc-sem4-vlsi','VLSI Design','EC207','B.Tech','ENC',4,'A'),
('btech-enc-sem4-dsp','Digital Signal Processing','EC208','B.Tech','ENC',4,'A'),
('btech-enc-sem5-wireless','Wireless Communication','EC301','B.Tech','ENC',5,'A'),
('btech-enc-sem5-embedded','Embedded Systems','EC302','B.Tech','ENC',5,'A'),
('btech-enc-sem5-optical','Optical Fiber Communication','EC303','B.Tech','ENC',5,'A'),
('btech-enc-sem5-antenna','Antenna Theory','EC304','B.Tech','ENC',5,'A'),
('btech-enc-sem6-5g','5G Networks','EC305','B.Tech','ENC',6,'A'),
('btech-enc-sem6-radar','Radar Engineering','EC306','B.Tech','ENC',6,'A'),
('btech-enc-sem6-iot','IoT Systems','EC307','B.Tech','ENC',6,'A'),
('btech-enc-sem6-fpga','FPGA Design','EC308','B.Tech','ENC',6,'A'),
('btech-enc-sem7-satellite','Satellite Communication','EC401','B.Tech','ENC',7,'A'),
('btech-enc-sem7-ml','ML for Signal Processing','EC402','B.Tech','ENC',7,'A'),
('btech-enc-sem7-asic','ASIC Design','EC403','B.Tech','ENC',7,'A'),
('btech-enc-sem7-elect','Elective','EC404','B.Tech','ENC',7,'A'),
('btech-enc-sem8-project','Major Project','EC498','B.Tech','ENC',8,'A'),
('btech-enc-sem8-adhoc','Ad-hoc Networks','EC405','B.Tech','ENC',8,'A'),
('btech-enc-sem8-nanotech','Nanoelectronics','EC406','B.Tech','ENC',8,'A'),
('btech-enc-sem8-ethics','Professional Ethics','HU401','B.Tech','ENC',8,'A'),

-- B.Sc Computer Science (6 semesters)
('bsc-cs-sem1-math','Mathematics I','MA101','B.Sc','CS',1,'A'),
('bsc-cs-sem1-prog','Programming in C','CS101','B.Sc','CS',1,'A'),
('bsc-cs-sem1-physics','Physics','PH101','B.Sc','CS',1,'A'),
('bsc-cs-sem1-english','English Communication','HU101','B.Sc','CS',1,'A'),
('bsc-cs-sem2-math2','Mathematics II','MA102','B.Sc','CS',2,'A'),
('bsc-cs-sem2-ds','Data Structures','CS102','B.Sc','CS',2,'A'),
('bsc-cs-sem2-digital','Digital Electronics','CS103','B.Sc','CS',2,'A'),
('bsc-cs-sem2-oop','OOP with Java','CS104','B.Sc','CS',2,'A'),
('bsc-cs-sem3-algo','Algorithms','CS201','B.Sc','CS',3,'A'),
('bsc-cs-sem3-os','Operating Systems','CS202','B.Sc','CS',3,'A'),
('bsc-cs-sem3-dbms','Database Management','CS203','B.Sc','CS',3,'A'),
('bsc-cs-sem3-web','Web Design','CS204','B.Sc','CS',3,'A'),
('bsc-cs-sem4-cn','Computer Networks','CS205','B.Sc','CS',4,'A'),
('bsc-cs-sem4-se','Software Engineering','CS206','B.Sc','CS',4,'A'),
('bsc-cs-sem4-python','Python Programming','CS207','B.Sc','CS',4,'A'),
('bsc-cs-sem4-graphics','Computer Graphics','CS208','B.Sc','CS',4,'A'),
('bsc-cs-sem5-ai','Artificial Intelligence','CS301','B.Sc','CS',5,'A'),
('bsc-cs-sem5-mobile','Mobile Computing','CS302','B.Sc','CS',5,'A'),
('bsc-cs-sem5-cloud','Cloud Computing','CS303','B.Sc','CS',5,'A'),
('bsc-cs-sem5-cyber','Cyber Security','CS304','B.Sc','CS',5,'A'),
('bsc-cs-sem6-project','Project Work','CS498','B.Sc','CS',6,'A'),
('bsc-cs-sem6-ml','Machine Learning','CS305','B.Sc','CS',6,'A'),
('bsc-cs-sem6-iot','Internet of Things','CS306','B.Sc','CS',6,'A'),
('bsc-cs-sem6-ethics','Professional Ethics','HU401','B.Sc','CS',6,'A'),

-- BCA (Bachelor of Computer Applications, 6 semesters)
('bca-sem1-math','Business Mathematics','MA101','BCA','General',1,'A'),
('bca-sem1-prog','C Programming','CS101','BCA','General',1,'A'),
('bca-sem1-intro','Introduction to Computers','CS102','BCA','General',1,'A'),
('bca-sem1-comm','Communication Skills','HU101','BCA','General',1,'A'),
('bca-sem2-math2','Discrete Mathematics','MA102','BCA','General',2,'A'),
('bca-sem2-ds','Data Structures','CS103','BCA','General',2,'A'),
('bca-sem2-dbms','Database Management','CS104','BCA','General',2,'A'),
('bca-sem2-web','Web Development','CS105','BCA','General',2,'A'),
('bca-sem3-algo','Algorithms','CS201','BCA','General',3,'A'),
('bca-sem3-os','Operating Systems','CS202','BCA','General',3,'A'),
('bca-sem3-java','Java Programming','CS203','BCA','General',3,'A'),
('bca-sem3-network','Computer Networks','CS204','BCA','General',3,'A'),
('bca-sem4-se','Software Engineering','CS205','BCA','General',4,'A'),
('bca-sem4-python','Python Programming','CS206','BCA','General',4,'A'),
('bca-sem4-mobile','Mobile Application Dev','CS207','BCA','General',4,'A'),
('bca-sem4-graphics','Computer Graphics','CS208','BCA','General',4,'A'),
('bca-sem5-ai','Artificial Intelligence','CS301','BCA','General',5,'A'),
('bca-sem5-cloud','Cloud Computing','CS302','BCA','General',5,'A'),
('bca-sem5-cyber','Cyber Security','CS303','BCA','General',5,'A'),
('bca-sem5-react','React & Frontend Frameworks','CS304','BCA','General',5,'A'),
('bca-sem6-project','Final Year Project','CS498','BCA','General',6,'A'),
('bca-sem6-ml','Machine Learning Basics','CS305','BCA','General',6,'A'),
('bca-sem6-erp','ERP Systems','CS306','BCA','General',6,'A'),
('bca-sem6-ethics','Ethics in Computing','HU401','BCA','General',6,'A'),

-- MCA (Master of Computer Applications, 4 semesters)
('mca-sem1-dsa','Advanced Data Structures','MCA101','MCA','General',1,'A'),
('mca-sem1-algo','Advanced Algorithms','MCA102','MCA','General',1,'A'),
('mca-sem1-dbms','Advanced DBMS','MCA103','MCA','General',1,'A'),
('mca-sem1-java','Advanced Java','MCA104','MCA','General',1,'A'),
('mca-sem1-math','Discrete Mathematics','MCA105','MCA','General',1,'A'),
('mca-sem2-os','Advanced Operating Systems','MCA201','MCA','General',2,'A'),
('mca-sem2-cn','Advanced Networks','MCA202','MCA','General',2,'A'),
('mca-sem2-se','Advanced Software Engineering','MCA203','MCA','General',2,'A'),
('mca-sem2-ml','Machine Learning','MCA204','MCA','General',2,'A'),
('mca-sem2-cloud','Cloud Architecture','MCA205','MCA','General',2,'A'),
('mca-sem3-ai','Artificial Intelligence','MCA301','MCA','General',3,'A'),
('mca-sem3-bigdata','Big Data Systems','MCA302','MCA','General',3,'A'),
('mca-sem3-cyber','Network Security','MCA303','MCA','General',3,'A'),
('mca-sem3-mobile','Mobile Computing','MCA304','MCA','General',3,'A'),
('mca-sem3-internship','Industrial Training','MCA305','MCA','General',3,'A'),
('mca-sem4-project','Major Project','MCA498','MCA','General',4,'A'),
('mca-sem4-dl','Deep Learning','MCA401','MCA','General',4,'A'),
('mca-sem4-blockchain','Blockchain Applications','MCA402','MCA','General',4,'A'),
('mca-sem4-devops','DevOps & CI/CD','MCA403','MCA','General',4,'A'),
('mca-sem4-ethics','Research Ethics','MCA404','MCA','General',4,'A'),

-- M.Sc Computer Science (4 semesters)
('msc-cs-sem1-algo','Advanced Algorithms','MSC101','M.Sc','CS',1,'A'),
('msc-cs-sem1-ml','Machine Learning','MSC102','M.Sc','CS',1,'A'),
('msc-cs-sem1-dbms','Advanced DBMS','MSC103','M.Sc','CS',1,'A'),
('msc-cs-sem1-theory','Theory of Computation','MSC104','M.Sc','CS',1,'A'),
('msc-cs-sem2-dl','Deep Learning','MSC201','M.Sc','CS',2,'A'),
('msc-cs-sem2-bigdata','Big Data Analytics','MSC202','M.Sc','CS',2,'A'),
('msc-cs-sem2-cloud','Cloud & Distributed Systems','MSC203','M.Sc','CS',2,'A'),
('msc-cs-sem2-cv','Computer Vision','MSC204','M.Sc','CS',2,'A'),
('msc-cs-sem3-nlp','Natural Language Processing','MSC301','M.Sc','CS',3,'A'),
('msc-cs-sem3-cyber','Advanced Cyber Security','MSC302','M.Sc','CS',3,'A'),
('msc-cs-sem3-rl','Reinforcement Learning','MSC303','M.Sc','CS',3,'A'),
('msc-cs-sem3-research','Research Methodology','MSC304','M.Sc','CS',3,'A'),
('msc-cs-sem4-project','Dissertation','MSC498','M.Sc','CS',4,'A'),
('msc-cs-sem4-ai','AI Ethics & Governance','MSC401','M.Sc','CS',4,'A'),
('msc-cs-sem4-quantum','Quantum Computing','MSC402','M.Sc','CS',4,'A'),
('msc-cs-sem4-elect','Advanced Elective','MSC403','M.Sc','CS',4,'A'),

-- MBA (Master of Business Administration, 4 semesters)
('mba-sem1-mgmt','Principles of Management','MBA101','MBA','General',1,'A'),
('mba-sem1-accounting','Financial Accounting','MBA102','MBA','General',1,'A'),
('mba-sem1-marketing','Marketing Management','MBA103','MBA','General',1,'A'),
('mba-sem1-economics','Managerial Economics','MBA104','MBA','General',1,'A'),
('mba-sem1-stats','Business Statistics','MBA105','MBA','General',1,'A'),
('mba-sem2-finance','Corporate Finance','MBA201','MBA','General',2,'A'),
('mba-sem2-hrm','Human Resource Management','MBA202','MBA','General',2,'A'),
('mba-sem2-ops','Operations Management','MBA203','MBA','General',2,'A'),
('mba-sem2-it','IT for Managers','MBA204','MBA','General',2,'A'),
('mba-sem2-ethics','Business Ethics','MBA205','MBA','General',2,'A'),
('mba-sem3-strategy','Strategic Management','MBA301','MBA','General',3,'A'),
('mba-sem3-entrepreneurship','Entrepreneurship','MBA302','MBA','General',3,'A'),
('mba-sem3-intl','International Business','MBA303','MBA','General',3,'A'),
('mba-sem3-analytics','Business Analytics','MBA304','MBA','General',3,'A'),
('mba-sem3-internship','Summer Internship','MBA305','MBA','General',3,'A'),
('mba-sem4-project','Final Project','MBA498','MBA','General',4,'A'),
('mba-sem4-leadership','Leadership & Change','MBA401','MBA','General',4,'A'),
('mba-sem4-supply','Supply Chain Management','MBA402','MBA','General',4,'A'),
('mba-sem4-digital','Digital Marketing','MBA403','MBA','General',4,'A'),
('mba-sem4-elect','Specialisation Elective','MBA404','MBA','General',4,'A')

ON CONFLICT (id) DO NOTHING;
